version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: users_database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - database_network

networks:
  database_network:
    name: database_network